from __future__ import annotations

"""Portable, evidence-bound Anchor Blueprint projection.

The Blueprint is a downstream reconstruction handoff. It never replaces the
canonical SCAN database and never upgrades PARTIAL/UNKNOWN evidence into fact.
"""

from collections import Counter
from hashlib import sha256
import json
from pathlib import Path
from typing import Any

from .conformance_contract import build_conformance_manifest, render_manifest_block

BLUEPRINT_SCHEMA = "scan-anchor-blueprint-md/0.4"


def _json(value: Any, default: Any) -> Any:
    if isinstance(value, (dict, list)):
        return value
    if value in (None, ""):
        return default
    try:
        return json.loads(value)
    except (TypeError, json.JSONDecodeError):
        return default


def _attrs(row: dict[str, Any]) -> dict[str, Any]:
    value = row.get("attributes")
    if isinstance(value, dict):
        return value
    parsed = _json(row.get("attributes_json"), {})
    return parsed if isinstance(parsed, dict) else {}


def _rows(store, table: str, order: str) -> list[dict[str, Any]]:
    try:
        return [dict(row) for row in store.query(f"SELECT * FROM {table} ORDER BY {order}")]
    except Exception:
        return []


def _cell(value: Any, limit: int = 180) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        value = json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    text = " ".join(str(value).split()).replace("|", "\\|")
    return text if len(text) <= limit else text[: limit - 1] + "…"


def app_name_from_specimen(specimen: dict[str, Any]) -> str:
    raw = str(
        specimen.get("repository")
        or specimen.get("specimen_id")
        or specimen.get("root")
        or "application"
    ).rstrip("/")
    return raw.rsplit("/", 1)[-1].removesuffix(".git") or "application"


def blueprint_filename(specimen: dict[str, Any]) -> str:
    return f"{app_name_from_specimen(specimen)} Anchor Blueprint.md"


def _node_table(rows: list[dict[str, Any]], kinds: set[str], *, limit: int = 240) -> list[str]:
    selected = [row for row in rows if str(row.get("kind")) in kinds][:limit]
    if not selected:
        return ["_No mechanically supported entries in this category._", ""]
    out = [
        "| Kind | Name | Coverage | Key evidence |",
        "|---|---|---|---|",
    ]
    for row in selected:
        attrs = _attrs(row)
        key = (
            attrs.get("text")
            or attrs.get("shortcut")
            or attrs.get("surface_type")
            or attrs.get("effect_type")
            or attrs.get("capability")
            or attrs.get("boundary_type")
            or attrs.get("operation")
            or attrs.get("condition")
            or attrs.get("initial_value")
            or attrs.get("system")
            or attrs.get("module")
            or row.get("path")
        )
        out.append(
            f"| `{_cell(row.get('kind'))}` | {_cell(row.get('name'))} | "
            f"`{_cell(row.get('coverage') or 'UNKNOWN')}` | {_cell(key)} |"
        )
    out.append("")
    return out


def render_agent_blueprint(
    store,
    specimen: dict[str, Any],
    *,
    engine_version: str,
    snapshot=None,
    scan_summary: dict[str, Any] | None = None,
) -> str:
    nodes = _rows(store, "nodes", "kind,path,name,id")
    findings = _rows(store, "findings", "kind,title,id")
    completeness = (
        list(snapshot.completeness)
        if snapshot is not None
        else list(store.completeness_dimensions())
    )
    app = app_name_from_specimen(specimen)
    manifest = build_conformance_manifest(
        store,
        specimen,
        engine_version=engine_version,
        blueprint_schema=BLUEPRINT_SCHEMA,
        snapshot=snapshot,
    )

    coverage_counts = Counter(str(row.get("coverage") or "UNKNOWN") for row in nodes)
    fingerprint = specimen.get("fingerprint")
    if isinstance(fingerprint, dict):
        fingerprint = fingerprint.get("value")

    lines = [
        f"# {app} Anchor Blueprint",
        "",
        f"Schema: `{BLUEPRINT_SCHEMA}`  ",
        f"Generated by: `scan-software-body/{engine_version}`  ",
        f"Specimen fingerprint: `{_cell(fingerprint or 'unknown', 120)}`",
        "",
        "## Reconstruction contract",
        "",
        "Recreate the evidence-supported behavior and human-facing semantics, not the original source layout. "
        "The canonical SCAN evidence remains authoritative. MAPPED facts may become hard reconstruction "
        "contracts; PARTIAL, BLOCKED, and UNKNOWN findings remain uncertainty and must not be silently promoted.",
        "",
        "Ordinary SCAN is static/read-only. This Blueprint does **not** claim runtime, pixel, timing, network, "
        "or performance equivalence unless separate evidence establishes it.",
        "",
        "## Coverage snapshot",
        "",
        f"- Canonical node coverage: `{dict(sorted(coverage_counts.items()))}`",
        f"- Embedded required conformance contracts: **{manifest['summary']['required_contract_count']}**",
        f"- Advisory source observations: **{manifest['summary']['advisory_contract_count']}**",
        "",
        "| Dimension | State |",
        "|---|---|",
    ]
    for dim in completeness:
        lines.append(f"| {_cell(dim.get('key') or dim.get('label'))} | `{_cell(dim.get('state') or 'UNKNOWN')}` |")
    lines += ["", "## Human interaction surface", ""]
    lines += _node_table(nodes, {
        "human_surface", "surface_reference", "surface_factory_output",
        "human_surface_container", "component_instance", "visual_contract", "visual_variant",
    })
    lines += ["## Entrances, events, state, and routing", ""]
    lines += _node_table(nodes, {
        "entry_point", "mount_point", "event", "handler_reference", "dispatch_route",
        "input_domain", "guard", "state_member", "member_symbol", "state_change",
    })
    lines += ["## Effects, persistence, and NEST boundary", ""]
    lines += _node_table(nodes, {
        "effect", "nest_boundary", "environment_boundary", "framework_capability",
        "persistence_provider", "persistence_operation", "capability_factory",
        "extension_receptor", "extension_receptor_candidate", "async_task",
    })
    lines += ["## Build and dependency anatomy", ""]
    lines += _node_table(nodes, {
        "build_script", "build_target", "dependency_reference", "module_reference",
        "resource", "resource_reference",
    })
    lines += ["## Explicit uncertainty and findings", ""]
    if findings:
        lines += [
            "| Finding | State | Detail |",
            "|---|---|---|",
        ]
        for row in findings[:240]:
            attrs = _attrs(row)
            lines.append(
                f"| {_cell(row.get('title'))} | `{_cell(row.get('coverage') or row.get('state') or 'UNKNOWN')}` | "
                f"{_cell(attrs.get('meaning') or attrs.get('detail') or attrs.get('error'))} |"
            )
        lines.append("")
    else:
        lines += ["_No findings were emitted._", ""]

    lines += [
        "## Machine-readable conformance manifest",
        "",
        "The block below is intentionally embedded in this same portable Markdown handoff. A later SCAN "
        "instance can rescan a reconstruction and compare mechanically supported contracts without needing "
        "the original source repository.",
        "",
        render_manifest_block(manifest),
        "",
        "## Limits",
        "",
        "- Source paths and line numbers are provenance, not reconstruction layout requirements.",
        "- Static conformance does not establish visual/pixel/timing/runtime equivalence.",
        "- NEST availability is not the same as BODY coupling, authorization, current use, or observed success.",
        "- Unknowns survive the handoff.",
        "",
    ]
    return "\n".join(lines)


def export_agent_blueprint(
    store,
    specimen: dict[str, Any],
    output_path: Path | None = None,
    *,
    engine_version: str,
    snapshot=None,
    scan_summary: dict[str, Any] | None = None,
) -> dict[str, Any]:
    output_path = Path(output_path) if output_path is not None else Path(blueprint_filename(specimen))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = render_agent_blueprint(
        store,
        specimen,
        engine_version=engine_version,
        snapshot=snapshot,
        scan_summary=scan_summary,
    )
    output_path.write_text(text, encoding="utf-8")
    return {
        "schema_version": BLUEPRINT_SCHEMA,
        "file": output_path.name,
        "app_name": app_name_from_specimen(specimen),
        "bytes": len(text.encode("utf-8")),
        "sha256": sha256(text.encode("utf-8")).hexdigest(),
        "runtime_observation_claimed": False,
        "purpose": "single-file coding-agent reconstruction handoff",
    }
